### ISSUE TITLE
getbugs raises TypeError when some bugs exist & some don't

### ISSUE THREAD

**Issue by ddraayer** [python-bugzilla/python-bugzilla#104]
When I give `getbugs` a list of two bug ids, where one references a real bug and one doesn't, I get a traceback:
```
>>> bugz.getbugs([34567, 98765])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[redacted]/lib/python3.7/site-packages/bugzilla/base.py", line 1085, in getbugs
    permissive=permissive)
  File "[redacted]/lib/python3.7/site-packages/bugzilla/base.py", line 1045, in _getbugs
    if i in self._listify(valdict.get("alias", None)):
TypeError: argument of type 'NoneType' is not iterable
```

If I give it ids for two non-existent bugs, the problem doesn't occur:
```
>>> bugz.getbugs([94567, 98765])
[None, None]
```
This is happening in version 2.2.0.

**Comment by crobinso** [comment]
Thanks for the report. Should be fixed in git now

**Comment by ddraayer** [comment]
Thanks for the quick fix.
