### ISSUE TITLE
Explicitly error if bugzilla instance doesn't support query_format=advanced/--from-url

### ISSUE THREAD

**Issue by mfrodl** [python-bugzilla/python-bugzilla#11]
When making certain requests to Apache Bugzilla, the `bugzilla` command fails and produces a traceback even though the URL the query is created from returns a correct bug list. I am not sure what exactly is going on in here but `bugzilla` should at least finish is a graceful, non-tracebacky way.

```
$ bugzilla --bugzilla https://bz.apache.org/bugzilla/xmlrpc.cgi --debug query --from-url 'https://bz.apache.org/bugzilla/buglist.cgi?f1=reporter&o1=equals&v1=mfrodl%40redhat.com&query_format=advanced'
[16:35:11] DEBUG (bugzilla:1168) Launched with command line: /usr/bin/bugzilla --bugzilla https://bz.apache.org/bugzilla/xmlrpc.cgi --debug query --from-url https://bz.apache.org/bugzilla/buglist.cgi?f1=reporter&o1=equals&v1=mfrodl%40redhat.com&query_format=advanced
[16:35:11] INFO (bugzilla:1184) Connecting to https://bz.apache.org/bugzilla/xmlrpc.cgi
[16:35:11] INFO (bugzilla:1187) Autodetecting Bugzilla type
[16:35:11] DEBUG (__init__:39) Detecting subclass for https://bz.apache.org/bugzilla/xmlrpc.cgi
[16:35:11] DEBUG (__init__:57) Checking for Red Hat Bugzilla extension
[16:35:12] DEBUG (__init__:63) rhbz=False
[16:35:12] DEBUG (__init__:67) Checking return value of Bugzilla.version()
[16:35:13] DEBUG (__init__:72) bzversion='4.4.10'
[16:35:13] DEBUG (__init__:83) No explicit match for 4.4.10, using latest bz4
[16:35:13] INFO (__init__:114) Chose subclass Bugzilla44 v0.1
[16:35:13] DEBUG (base:422) Using tokenfile=/home/mfrodl/.bugzillatoken
[16:35:13] DEBUG (base:539) Using cookiefile=/home/mfrodl/.bugzillacookies
[16:35:13] DEBUG (base:1193) Calling Bug.search with: {'f1': 'reporter', 'v1': 'mfrodl@redhat.com', 'query_format': 'advanced', 'include_fields': ['assigned_to', 'id', 'status', 'summary'], 'o1': 'equals'}
[16:35:15] DEBUG (bugzilla:1307) 
Traceback (most recent call last):
  File "/usr/bin/bugzilla", line 1300, in <module>
    main()
  File "/usr/bin/bugzilla", line 1265, in main
    buglist = _do_query(bz, opt, parser)
  File "/usr/bin/bugzilla", line 753, in _do_query
    return bz.query(q)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 1203, in query
    r = self._query(query)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 1194, in _query
    return self._proxy.Bug.search(query)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 168, in _ServerProxy__request
    ret = ServerProxy._ServerProxy__request(self, methodname, params)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 259, in request
    return self._request_helper(url, request_body)
  File "/usr/lib/python2.7/site-packages/bugzilla/base.py", line 245, in _request_helper
    raise sys.exc_info()[1]
Fault: <Fault 53: 'query_format is not a valid parameter for the Bugzilla::Bug::match function.'>

Server error: <Fault 53: 'query_format is not a valid parameter for the Bugzilla::Bug::match function.'>```

**Comment by crobinso** [comment]
Thanks for the report. Querying with URL format is a bugzilla.redhat.com extension so isn't going to work for apache bugzilla. We can use this issue to track making that more explicit, in fact we can probably just throw an error unless we detect bugzilla.redhat.com

**Comment by mfrodl** [comment]
This traceback is not limited to `--field-url` queries; it can equally well be generated with:

`bugzilla --bugzilla https://bz.apache.org/bugzilla/xmlrpc.cgi --debug query --field=f1=reporter --field=o1=equals --field=v1=mfrodl@redhat.com --field=query_format=advanced`

**Comment by crobinso** [comment]
Yes it's not specifically about --from-url; it's that bugzilla.redhat.com has an extension to accept URL style field names (query_format=advanced, and others) over the XMLRPC API. --from-url just decomposes a URL to a python dict to pass to the XMLRPC API. If you break the URL down into individual --field= calls you are largely going to get the same result

Some URL parameters _are_ valid XMLRPC query param names, so it might work for some cases, if you strip out the query_format=advanced bit that is always attached to URL query strings
