### ISSUE TITLE
Failed to connect to bugzilla

### ISSUE THREAD

**Issue by pypingou** [python-bugzilla/python-bugzilla#115]
Using the current master branch (commit 323dc55207b9853603247c6f6d7dab276c7136e6) this is what I get:

`````python
>>> import bugzilla
>>> server = bugzilla.Bugzilla(
...     url="https://bugzilla.redhat.com",
...     user="email@user...",
...     password="xxxxx",
... )
Traceback (most recent call last):
  File "<input>", line 4, in <module>
    password="xxxxx",
  File "/home/pingou/repos/gitrepo/python-bugzilla/bugzilla/base.py", line 255, in __init__
    self.connect(url)
  File "/home/pingou/repos/gitrepo/python-bugzilla/bugzilla/base.py", line 519, in connect
    self.login()
  File "/home/pingou/repos/gitrepo/python-bugzilla/bugzilla/base.py", line 615, in login
    BugzillaError.get_bugzilla_error_string(e))
bugzilla.exceptions.BugzillaError: Login failed: cannot marshal None unless allow_none is enabled
````

**Comment by pypingou** [comment]
The same code works with ``python3-bugzilla-2.3.0-1.fc30.noarch``

**Comment by pypingou** [comment]
Not sure if it's related but:
````python
>>> import bugzilla
>>> server = bugzilla.Bugzilla(
...     url="https://bugzilla.redhat.com",
... )
>>> server.logged_in
True
````

**Comment by crobinso** [comment]
Thanks for the report, I broke that in some recent refactoring while filling out the test coverage, but didn't actually confirm the test output was valid :) Fixed now

**Comment by pypingou** [comment]
> didn't actually confirm the test output was valid 

Been there, done that :)

Thanks for the fix!
