### ISSUE TITLE
pip install bugzilla : Update the pip source file (version 1.0.0) for python-bugzilla .  [if you still support the pip package]

### ISSUE THREAD

**Issue by MalloZup** [python-bugzilla/python-bugzilla#12]
Hi all,

do you still continue to support the pip version of the package (on python) ?
installing with pip an user get:
```

Collecting bugzilla
  Using cached bugzilla-1.0.0.tar.gz
Installing collected packages: bugzilla
  Running setup.py install for bugzilla ... done
Successfully installed bugzilla-1.0.0
```
This source isn't usable, the installation/modules/depend. aren't right.

```
python
Python 2.7.9 (default, Dec 13 2014, 18:02:08) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import bugzilla
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/bugzilla.py", line 13, in <module>
    import requests
ImportError: No module named requests

```
And the 1.0.0 isn't the current-stable version.
 
With clone from here(git repo), the package work well.

Thank you in advance,

Best

**Comment by crobinso** [comment]
That pip 'bugzilla' module is a different project. Ours is on pip as python-bugzilla

**Comment by MalloZup** [comment]
ok thx crob.
