### ISSUE TITLE
how to get the closed time of a bug by using bugzilla?

### ISSUE THREAD

**Issue by SuYanqi** [python-bugzilla/python-bugzilla#141]
It's excellent that I can get the CreationTime and LastChangeTime of a bug. But how can I get the closed time of a bug?
<img width="815" alt="Screen Shot 2020-11-24 at 9 13 26 PM" src="https://user-images.githubusercontent.com/26957616/100099560-92f05f80-2e9a-11eb-9915-3c2b594df675.png">

**Comment by crobinso** [comment]
The Bugzilla server API does not provide it directly. See the list of values here: https://bugzilla.readthedocs.io/en/latest/api/core/v1/bug.html#get-bug

If you just want to use that field to query for bugs closed after a certain time, you can use the URL query support: https://blog.wikichoon.com/2014/05/invoking-bugzilla-query-url-from.html

If you need to fetch that value directly, you will need to process the Bugzilla.bugs_history_raw() output and find the time that the state was changed to CLOSED. The history data fields are listed here: https://bugzilla.readthedocs.io/en/latest/api/core/v1/bug.html#get-bug

**Comment by SuYanqi** [comment]
Thank you for your reply. It works well for me. And I meet one more problem. When I crawler bugs from Mozilla by using my computer, it is fine. However, when I put it on the remote server, an exception happens: Traceback (most recent call last):
  File "queryBugsFromCPC.py", line 40, in <module>
    CPC = getBugsFromCPC(URL,CPCfilepath, 0, 0, 0)#0 1 16没爬取
  File "queryBugsFromCPC.py", line 32, in getBugsFromCPC
    queryBugs.getBugs(URL, className, proName, comName)
  File "/home/fdse/project/bugzilla/python-bugzilla-master/crawlerBugzilla/queryBugs.py", line 15, in getBugs
    bzapi = bugzilla.Bugzilla(URL)
  File "/home/fdse/project/bugzilla/python-bugzilla-master/bugzilla/base.py", line 250, in __init__
    self._setcookiefile(cookiefile)
  File "/home/fdse/project/bugzilla/python-bugzilla-master/bugzilla/base.py", line 371, in _setcookiefile
    self._cookiecache.set_filename(cookiefile)
  File "/home/fdse/project/bugzilla/python-bugzilla-master/bugzilla/_authfiles.py", line 211, in set_filename
    self._cookiejar = self._build_cookiejar(cookiefile)
  File "/home/fdse/project/bugzilla/python-bugzilla-master/bugzilla/_authfiles.py", line 207, in _build_cookiejar
    raise BugzillaError(msg) from None
bugzilla.exceptions.BugzillaError: cookiefile=/home/fdse/.cache/python-bugzilla/bugzillacookies not in Mozilla format

**Comment by SuYanqi** [comment]
Thank you for your reply. It works well for me.
