### ISSUE TITLE
Cannot get comments for bugs in mozilla. Error: xml.parsers.expat.ExpatError: not well-formed (invalid token): line 8, column 150

### ISSUE THREAD

**Issue by VikingStudyHard** [python-bugzilla/python-bugzilla#155]
When I am collecting the comments with these codes:
```python
import bugzilla
bugzilla_api = bugzilla.Bugzilla("bugzilla.mozilla.org")
bug_obj = bugzilla_api.getbug(1531344)
bug_comment = bug_obj.getcomments()
```
the errors come out: 
```python
>>> bug_comment = bug_obj.getcomments()
Traceback (most recent call last):
  File "/Users/my_name/miniconda3/lib/python3.8/site-packages/bugzilla/_backendxmlrpc.py", line 47, in __request_helper
    return self.parse_response(response)
  File "/Users/my_name/miniconda3/lib/python3.8/site-packages/bugzilla/_backendxmlrpc.py", line 77, in parse_response
    parser.feed(msg)
  File "/Users/my_name/miniconda3/lib/python3.8/xmlrpc/client.py", line 438, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 8, column 150

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/my_name/miniconda3/lib/python3.8/site-packages/bugzilla/bug.py", line 290, in getcomments
    comment_list = self.bugzilla.get_comments([self.bug_id])
  File "/Users/my_name/miniconda3/lib/python3.8/site-packages/bugzilla/base.py", line 1156, in get_comments
    return self._backend.bug_comments(idlist, {})
  File "/Users/my_name/miniconda3/lib/python3.8/site-packages/bugzilla/_backendxmlrpc.py", line 178, in bug_comments
    return self._xmlrpc_proxy.Bug.comments(data)
  File "/Users/my_name/miniconda3/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/Users/my_name/miniconda3/lib/python3.8/site-packages/bugzilla/_backendxmlrpc.py", line 132, in _ServerProxy__request
    ret = ServerProxy._ServerProxy__request(self, methodname, (newparams,))
  File "/Users/my_name/miniconda3/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/Users/my_name/miniconda3/lib/python3.8/site-packages/bugzilla/_backendxmlrpc.py", line 100, in request
    return self.__request_helper(url, request_body)
  File "/Users/my_name/miniconda3/lib/python3.8/site-packages/bugzilla/_backendxmlrpc.py", line 63, in __request_helper
    raise e
  File "/Users/my_name/miniconda3/lib/python3.8/site-packages/bugzilla/_backendxmlrpc.py", line 47, in __request_helper
    return self.parse_response(response)
  File "/Users/my_name/miniconda3/lib/python3.8/site-packages/bugzilla/_backendxmlrpc.py", line 77, in parse_response
    parser.feed(msg)
  File "/Users/my_name/miniconda3/lib/python3.8/xmlrpc/client.py", line 438, in feed
    self._parser.Parse(data, 0)
bugzilla.exceptions.BugzillaError: not well-formed (invalid token): line 8, column 150
```

Thanks!

**Comment by crobinso** [comment]
Thanks for the report. Trying using bugzilla.mozilla.org/rest, that seems to work. mozilla is deprecating their xmlrpc interface, so maybe it's some breakage on their side
