### ISSUE TITLE
bugzilla tokens are worse than useless with `bugzilla.redhat.com` nowadays

### ISSUE THREAD

**Issue by AdamWill** [python-bugzilla/python-bugzilla#162]
I have a script that tries to use `bzapi.logged_in` to decide whether to log in, but if you're not logged in, it seems this causes a crash:

    Traceback (most recent call last):
      File "/home/adamw/local/qa-misc/./updatetrackers", line 232, in <module>
        run()
      File "/home/adamw/local/qa-misc/./updatetrackers", line 217, in run
        if not bzapi.logged_in:
      File "/usr/lib/python3.10/site-packages/bugzilla/base.py", line 720, in logged_in
        raise e
      File "/usr/lib/python3.10/site-packages/bugzilla/base.py", line 714, in logged_in
        self._backend.user_get({"ids": [1]})
      File "/usr/lib/python3.10/site-packages/bugzilla/_backendxmlrpc.py", line 222, in user_get
        return self._xmlrpc_proxy.User.get(paramdict)
      File "/usr/lib64/python3.10/xmlrpc/client.py", line 1122, in __call__
        return self.__send(self.__name, args)
      File "/usr/lib/python3.10/site-packages/bugzilla/_backendxmlrpc.py", line 125, in _ServerProxy__request
        ret = ServerProxy._ServerProxy__request(
      File "/usr/lib64/python3.10/xmlrpc/client.py", line 1464, in __request
        response = self.__transport.request(
      File "/usr/lib/python3.10/site-packages/bugzilla/_backendxmlrpc.py", line 100, in request
        return self.__request_helper(url, request_body)
      File "/usr/lib/python3.10/site-packages/bugzilla/_backendxmlrpc.py", line 47, in __request_helper
        return self.parse_response(response)
      File "/usr/lib/python3.10/site-packages/bugzilla/_backendxmlrpc.py", line 84, in parse_response
        return unmarshaller.close()
      File "/usr/lib64/python3.10/xmlrpc/client.py", line 668, in close
        raise Fault(**self._stack[0])
    xmlrpc.client.Fault: <Fault Client: "Application failed during request deserialization: 32000: The method 'User.get' is not supported without using API keys and the the authentication header. See https://bugzilla.redhat.com/docs/en/html/api/core/v1/general.html#authentication for details on using the 'Authorization' header. at /usr/share/perl5/vendor_perl/SOAP/Lite.pm line 2855.\n">

**Comment by crobinso** [comment]
Sorry for the late reply.

This is still relevant with git. This is triggered by passing in an auth token (like `bugzilla login` will cache to `~/.cache/python-bugzilla/bugzillatoken`) but NOT an API key (like `bugzilla login --api-key` will save to `~/.config/python-bugzilla/bugzillarc`)

Actually it looks like `bugzilla.redhat.com` completely rejects token auth these days. If you have a valid token but no API key passed, it won't even let you do basic `Bug.get` call. So seems tokenfiles are entirely useless nowadays. We should change something in python-bugzilla to never use tokenfiles for redhat bugzillas.

**Comment by crobinso** [comment]
bugzilla devs agreed internally to disable User.login entirely. I think that's good enough. We can track progress here: https://bugzilla.redhat.com/show_bug.cgi?id=2263202
