### ISSUE TITLE
Bugzilla.fix_url() fails to extend GCC Bugzilla URL to an XMLRPC URL

### ISSUE THREAD

**Issue by yizhengx** [python-bugzilla/python-bugzilla#165]
https://github.com/python-bugzilla/python-bugzilla/blob/a7c324041175a4157823bc2332a046cc2a54d105/bugzilla/base.py#L137-L160

When I try to initialize Bugzilla with GCC Bugzilla url "gcc.gnu.org/bugzilla", it fails to initialize Bugzilla since it fails to extend the url to an XMLRPC url, but it works fine with "gcc.gnu.org/bugzilla/xmlrpc.cgi". Probably useful to enhance fix_url() to solve this type of urls.

```
Traceback (most recent call last):
  File "/Users/yizhengxie/Desktop/untitled_folder/test.py", line 19, in <module>
    bzapi = bugzilla.Bugzilla(URL_gcc)
  File "/Users/yizhengxie/Desktop/untitled_folder/bugzilla/base.py", line 251, in __init__
    self.connect(url)
  File "/Users/yizhengxie/Desktop/untitled_folder/bugzilla/base.py", line 526, in connect
    version = self._backend.bugzilla_version()["version"]
  File "/Users/yizhengxie/Desktop/untitled_folder/bugzilla/_backendxmlrpc.py", line 146, in bugzilla_version
    return self._xmlrpc_proxy.Bugzilla.version()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 1109, in __call__
    return self.__send(self.__name, args)
  File "/Users/yizhengxie/Desktop/untitled_folder/bugzilla/_backendxmlrpc.py", line 125, in _ServerProxy__request
    ret = ServerProxy._ServerProxy__request(
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 1450, in __request
    response = self.__transport.request(
  File "/Users/yizhengxie/Desktop/untitled_folder/bugzilla/_backendxmlrpc.py", line 100, in request
    return self.__request_helper(url, request_body)
  File "/Users/yizhengxie/Desktop/untitled_folder/bugzilla/_backendxmlrpc.py", line 63, in __request_helper
    raise e
  File "/Users/yizhengxie/Desktop/untitled_folder/bugzilla/_backendxmlrpc.py", line 47, in __request_helper
    return self.parse_response(response)
  File "/Users/yizhengxie/Desktop/untitled_folder/bugzilla/_backendxmlrpc.py", line 77, in parse_response
    parser.feed(msg)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/xmlrpc/client.py", line 438, in feed
    self._parser.Parse(data, 0)
bugzilla.exceptions.BugzillaError: mismatched tag: line 70, column 4
The URL may not be an XMLRPC URL: https://gcc.gnu.org/bugzilla
```

**Comment by crobinso** [comment]
Sorry for late response. I agree this is annoying. But it's been this way for 10+ years. I'm kind of afraid that it's possible someone could root their xmlrpc.cgi entrypoint at some custom path, and now our URL fixing logic would try to slap xmlrpc.cgi on the end of it and screw things up. Obviously we could work around that but we would have to potentially probe multiple URLs. We would also have to be mindful of the `/rest` path entrypoint too.

IMO it's not worth though, so I don't plan to fix this unless someone comes up with a more clever idea.
