### ISSUE TITLE
getbugs fails when one of the bug ids is not accesible

### ISSUE THREAD

**Issue by danigm** [python-bugzilla/python-bugzilla#222]
The field "permissive" in the `getbugs` api call does nothing. An exception is raised always when there's one invalid or not accesible bug id in the list.

**Comment by crazyscientist** [comment]
@danigm Thank you for reporting this. Could you provide us also with a short guide on how to reproduce? E.g. did you use XMLRPC or REST?

**Comment by crazyscientist** [comment]
Great. thank you.

**Comment by crazyscientist** [comment]
For comparison:
## REST
```python
>>> bz_r = Bugzilla("https://bugzilla.suse.com", force_rest=True)
>>> bz_r.getbugs([654591], permissive=True)
Traceback (most recent call last):
  File "/home/andi/workspace/python-bugzilla/bugzilla/_session.py", line 109, in request
    response.raise_for_status()
  File "/home/andi/virtualenvs/bz312/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://bugzilla.suse.com/rest/bug/654591?permissive=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/andi/workspace/python-bugzilla/bugzilla/_backendrest.py", line 76, in _op
    response = self._bugzillasession.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andi/workspace/python-bugzilla/bugzilla/_session.py", line 115, in request
    raise BugzillaHTTPError(
  File "/home/andi/workspace/python-bugzilla/bugzilla/_session.py", line 109, in request
    response.raise_for_status()
  File "/home/andi/virtualenvs/bz312/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
bugzilla.exceptions.BugzillaHTTPError: 401 Client Error: Unauthorized for url: https://bugzilla.suse.com/rest/bug/654591?permissive=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/andi/workspace/python-bugzilla/bugzilla/base.py", line 1150, in getbugs
    data = self._getbugs(idlist, include_fields=include_fields,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andi/workspace/python-bugzilla/bugzilla/base.py", line 1102, in _getbugs
    r = self._backend.bug_get(ids, aliases, getbugdata)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andi/workspace/python-bugzilla/bugzilla/_backendrest.py", line 122, in bug_get
    return self._get("/bug/%s" % id_list[0], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andi/workspace/python-bugzilla/bugzilla/_backendrest.py", line 85, in _get
    return self._op("GET", *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/andi/workspace/python-bugzilla/bugzilla/_backendrest.py", line 80, in _op
    self._handle_error(e)
  File "/home/andi/workspace/python-bugzilla/bugzilla/_backendrest.py", line 41, in _handle_error
    self._handle_error_response(response.text)
  File "/home/andi/workspace/python-bugzilla/bugzilla/_backendrest.py", line 51, in _handle_error_response
    raise BugzillaError(result["message"], code=result["code"])
bugzilla.exceptions.BugzillaError: You are not authorized to access bug #654591. To see this bug, you must first log in to an account with the appropriate permissions. (code=102)
```

## XMLRPC
```python
>>> bz_x = Bugzilla("https://bugzilla.suse.com", force_xmlrpc=True)
>>> bz_x.getbugs([654591], permissive=True)
[]
