### ISSUE TITLE
XML parser fails when fetching comments of a bug

### ISSUE THREAD

**Issue by mprpic** [python-bugzilla/python-bugzilla#24]
I'm trying to fetch comments of this bug: https://bugzilla.novell.com/show_bug.cgi?id=811793 . It fails when parsing the underlying XML as can be seen in the traceback below. Any ideas what could be causing this? I've run through 5k bugs like this and this is the only one that errs. The XML looks valid to me (https://paste.fedoraproject.org/438071/).

```
>>> from bugzilla import Bugzilla
>>> url = 'https://bugzilla.novell.com'
>>> BZ = Bugzilla(url)
>>> BZ.get_comments([811793])
Traceback (most recent call last):
  File "/home/mprpic/test_app/venv/lib/python3.4/site-packages/bugzilla/base.py", line 237, in _request_helper
    return self.parse_response(response)
  File "/home/mprpic/test_app/venv/lib/python3.4/site-packages/bugzilla/base.py", line 210, in parse_response
    parser.feed(response.text.encode('utf-8'))
  File "/opt/rh/rh-python34/root/usr/lib64/python3.4/xmlrpc/client.py", line 446, in feed
    self._parser.Parse(data, 0)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 60, column 49

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mprpic/test_app/venv/lib/python3.4/site-packages/bugzilla/base.py", line 1067, in get_comments
    return self._proxy.Bug.comments({'ids': idlist})
  File "/opt/rh/rh-python34/root/usr/lib64/python3.4/xmlrpc/client.py", line 1098, in __call__
    return self.__send(self.__name, args)
  File "/home/mprpic/test_app/venv/lib/python3.4/site-packages/bugzilla/base.py", line 168, in _ServerProxy__request
    ret = ServerProxy._ServerProxy__request(self, methodname, params)
  File "/opt/rh/rh-python34/root/usr/lib64/python3.4/xmlrpc/client.py", line 1428, in __request
    verbose=self.__verbose
  File "/home/mprpic/test_app/venv/lib/python3.4/site-packages/bugzilla/base.py", line 259, in request
    return self._request_helper(url, request_body)
  File "/home/mprpic/test_app/venv/lib/python3.4/site-packages/bugzilla/base.py", line 250, in _request_helper
    raise e
  File "/home/mprpic/test_app/venv/lib/python3.4/site-packages/bugzilla/base.py", line 237, in _request_helper
    return self.parse_response(response)
  File "/home/mprpic/test_app/venv/lib/python3.4/site-packages/bugzilla/base.py", line 210, in parse_response
    parser.feed(response.text.encode('utf-8'))
  File "/opt/rh/rh-python34/root/usr/lib64/python3.4/xmlrpc/client.py", line 446, in feed
    self._parser.Parse(data, 0)
bugzilla.base.BugzillaError: not well-formed (invalid token): line 60, column 49
```

**Comment by mprpic** [comment]
Turns out it's this line in comment 8 of this bug:
```
Frederic, do you have any idea what could create /var/run/nologin?
```
which gets turned to this in the XML:
```
Frederic, do you have any idea what could create \x1b/var/run/nologin?
```
The XML parser then chokes on the `\x1b` character.

**Comment by crobinso** [comment]
Thanks for the report. \x1b isn't a valid character in XML though:

http://stackoverflow.com/questions/404107/why-are-control-characters-illegal-in-xml-1-0

So I think bugzilla is generating invalid XML here and it's something that needs to be fixed on the bugzilla side. I tried entering that character into a comment in partner-bugzilla.redhat.com but it didn't stick, so maybe this is already fixed but bugzilla.novell.com needs to be updated?
