### ISSUE TITLE
Examples doesn't work - TypeError: __init__() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by gBopHuk** [python-bugzilla/python-bugzilla#28]
When I launch any scripts from an examples dir I get `"TypeError: __init__() takes exactly 1 argument (2 given)"`

```
$ python bug_autorefresh.py
Traceback (most recent call last):
  File "bug_autorefresh.py", line 18, in <module>
    bzapi = bugzilla.Bugzilla(URL)
TypeError: __init__() takes exactly 1 argument (2 given)

 $python getbug.py
Traceback (most recent call last):
  File "getbug.py", line 21, in <module>
    bzapi = bugzilla.Bugzilla(URL)
TypeError: __init__() takes exactly 1 argument (2 given)

$ python query.py
Traceback (most recent call last):
  File "query.py", line 20, in <module>
    bzapi = bugzilla.Bugzilla(URL)
TypeError: __init__() takes exactly 1 argument (2 given)

```

**Comment by crobinso** [comment]
Works fine here. What's the output of

python -c 'import bugzilla; print bugzilla, bugzilla.__version__'
