### ISSUE TITLE
XML parser error in `logged_in()` on Bugzilla 5

### ISSUE THREAD

**Issue by AdamWill** [python-bugzilla/python-bugzilla#29]
I decided to test some python-bugzilla scripts I have against the Red Hat testing instance of Bugzilla 5 (which is unfortunately RH-internal for now, but Cole, you should know where to find it). I can reliably crash it like this:

    [adamw@xps13k qa-misc (master *)]$ python3
    Python 3.5.2 (default, Sep 14 2016, 11:28:32) 
    [GCC 6.2.1 20160901 (Red Hat 6.2.1-1)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import bugzilla
    >>> bzapi = bugzilla.Bugzilla("beta.bugzilla.redhat.com/bugzilla")
    >>> bzapi.logged_in()
    Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/bugzilla/base.py", line 237, in _request_helper
        return self.parse_response(response)
      File "/usr/lib/python3.5/site-packages/bugzilla/base.py", line 210, in parse_response
        parser.feed(response.text.encode('utf-8'))
      File "/usr/lib64/python3.5/xmlrpc/client.py", line 438, in feed
        self._parser.Parse(data, 0)
    xml.parsers.expat.ExpatError: mismatched tag: line 94, column 4

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/lib/python3.5/site-packages/bugzilla/base.py", line 701, in logged_in
        self._proxy.User.get({'ids': []})
      File "/usr/lib64/python3.5/xmlrpc/client.py", line 1092, in __call__
        return self.__send(self.__name, args)
      File "/usr/lib/python3.5/site-packages/bugzilla/base.py", line 168, in _ServerProxy__request
        ret = ServerProxy._ServerProxy__request(self, methodname, params)
      File "/usr/lib64/python3.5/xmlrpc/client.py", line 1432, in __request
        verbose=self.__verbose
      File "/usr/lib/python3.5/site-packages/bugzilla/base.py", line 259, in request
        return self._request_helper(url, request_body)
      File "/usr/lib/python3.5/site-packages/bugzilla/base.py", line 250, in _request_helper
        raise e
      File "/usr/lib/python3.5/site-packages/bugzilla/base.py", line 237, in _request_helper
        return self.parse_response(response)
      File "/usr/lib/python3.5/site-packages/bugzilla/base.py", line 210, in parse_response
        parser.feed(response.text.encode('utf-8'))
      File "/usr/lib64/python3.5/xmlrpc/client.py", line 438, in feed
        self._parser.Parse(data, 0)
    bugzilla.base.BugzillaError: mismatched tag: line 94, column 4
    >>>

**Comment by ktdreyer** [comment]
Whoops an internal URL's there in the paste anyway :)

Adam, the following works for me with python-bugzilla-1.2.2-4.fc25 using the latest BZ 5 hostname:
```
bugzilla --nosslverify --bugzilla=https://beta-bugzilla.redhat.com/xmlrpc.cgi login
```

Is it working in your environment?

**Comment by crobinso** [comment]
Yeah the 'mismatch' issue is due to lacking /xmlrpc.cgi in the original URL. python-bugzilla only tries to add /xmlrpc.cgi if the URL doesn't have a path in it to begin with

**Comment by AdamWill** [comment]
Well, originally the script just had 'bugzilla.redhat.com' , because current Bugzilla doesn't have any subpath. I'd be surprised if this script was the only one like that. So if you just make the 'obvious' amendment - add the /bugzilla subpath - you suddenly hit this bug.

**Comment by crobinso** [comment]
Right, but that /bugzilla path is going away anyways, the new canonical location is going to be beta-bugzilla.redhat.com/xmlrpc.cgi, so it won't matter for long

**Comment by AdamWill** [comment]
Aha, OK. I wasn't sure whether that was the case.
