### ISSUE TITLE
package broken on bugzilla 4.4.1

### ISSUE THREAD

**Issue by caphrim007** [python-bugzilla/python-bugzilla#41]
Hi, I have a bugzilla running on 4.4.1 which the package works fine with if I use 1.2.2. If I use 2.1.0 though, I start getting these stack traces

```
Traceback (most recent call last):
  File "ok2.py", line 6, in <module>
    BZ.login('user', 'password')
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/bugzilla/base.py", line 608, in login
    ret = self._login(self.user, self.password)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/bugzilla/base.py", line 574, in _login
    return self._proxy.User.login({'login': user, 'password': password})
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/bugzilla/transport.py", line 100, in _ServerProxy__request
    ret = ServerProxy._ServerProxy__request(self, methodname, params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/bugzilla/transport.py", line 195, in request
    return self._request_helper(url, request_body)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/bugzilla/transport.py", line 158, in _request_helper
    url, data=request_body, **self.request_defaults)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/requests/sessions.py", line 549, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/q.py", line 279, in wrapper
    result = func(*args, **kwargs)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/requests/adapters.py", line 492, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error("(54, 'ECONNRESET')",))
```

This seems to happen whether I use the Bugzilla class or the Bugzilla44 class.

Any thoughts on why this might be occurring? I recognize that there are quite a number of changes between the two versions. Just curious if you have any insight.

**Comment by caphrim007** [comment]
here's another error that pops up

```
(ansible-2.0) SEA-ML-RUPP1:f5-common-python trupp$ python ok2.py 
Traceback (most recent call last):
  File "ok2.py", line 5, in <module>
    BZ = bugzilla.Bugzilla(url=URL, sslverify=SSLVERIFY)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/bugzilla/base.py", line 319, in __init__
    self._init_class_from_url()
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/bugzilla/base.py", line 334, in _init_class_from_url
    extensions = self._proxy.Bugzilla.extensions()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/bugzilla/transport.py", line 100, in _ServerProxy__request
    ret = ServerProxy._ServerProxy__request(self, methodname, params)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/bugzilla/transport.py", line 195, in request
    return self._request_helper(url, request_body)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/bugzilla/transport.py", line 158, in _request_helper
    url, data=request_body, **self.request_defaults)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/requests/sessions.py", line 549, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/q.py", line 279, in wrapper
    result = func(*args, **kwargs)
  File "/Users/trupp/src/envs/ansible-2.0/lib/python2.7/site-packages/requests/adapters.py", line 492, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

this one is raised before I even have a change to call `login`

**Comment by crobinso** [comment]
hmm not sure off hand. is this a public bugzilla instance I can try?

Maybe try a git bisect

git clone git://github.com/python-bugzilla/python-bugzilla
cd python-bugzilla
git bisect good v1.2.2
git bisect bad v2.1.0

Then reproduce, and enter git bisect good/bad depending on if you hit the issue. That should identify the offending commit which might give a hint

**Comment by caphrim007** [comment]
hey @crobinso. unfortunately it is not. I'll try bisecting and see where that goes. will open another issue referencing that one if i find anything.

**Comment by caphrim007** [comment]
@crobinso bisect reports that https://github.com/python-bugzilla/python-bugzilla/commit/fd0c66a6d343702df29edd8d4c34c3238aea8dfb was the first bad commit. I'll see if undoing that one makes the problem go away.

**Comment by caphrim007** [comment]
removing the merge that the bisect reported makes things work like a champ.

**Comment by crobinso** [comment]
hmm thanks for finding that. probably not a 'bug' in python-bugzilla since this is just enabling keepalive through python-requests, but we need to figure out what's going on.

are python-requests and python-urllib3 up to date?
does python-bugzilla fail immediately or does it have to timeout in some way?
do you have access to the python-bugzilla server? if so, do you know if http keepalive is enabled?

**Comment by caphrim007** [comment]
requests==2.18.1
urllib3==1.21.1

would those be considered up-to-date?

It takes about half a second to fail, and I haven't specifically set any timeout values.

I dont have direct access to the bugzilla server, but I know the person who does, so I can ask about the keepalive thing.

**Comment by crobinso** [comment]
Those versions are newer than mine at least :)

Unfortunately I don't know a ton about bugzilla server side of things. I think http keepalive is just an apache config and not anything bugzilla specific. Maybe try running requests just against the http server in general, independent of python-bugzilla, see if it fails: may be a general http config issue.

**Comment by caphrim007** [comment]
heh, ok.

I can repro this by using a requests Session object and calling multiple gets in succession. For example,

```
import requests
s = requests.Session()
foo = s.get('https://bugzilla.foo.com', verify=False)
foo = s.get('https://bugzilla.foo.com', verify=False)
foo = s.get('https://bugzilla.foo.com', verify=False)
foo = s.get('https://bugzilla.foo.com', verify=False)
```

It will routinely fail on the 2nd and 3rd attempts, but will periodically succeed at all attempt. Sure doesn't sound like a python-bugzilla problem. Will look at our server now.
