### ISSUE TITLE
Python 3.2 compatibility issue

### ISSUE THREAD

**Issue by abn** [python-bugzilla/python-bugzilla#48]
The bug module does not work under python 3.2.
```
/home/travis/build/python-bugzilla/python-bugzilla/.tox/py32/lib/python3.2/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '2.2.0-dev' to '2.2.0.dev0'
  normalized_version,
running test
Traceback (most recent call last):
  File "setup.py", line 213, in <module>
    "test" : TestCommand,
  File "/opt/python/3.2.5/lib/python3.2/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/3.2.5/lib/python3.2/distutils/dist.py", line 917, in run_commands
    self.run_command(cmd)
  File "/opt/python/3.2.5/lib/python3.2/distutils/dist.py", line 936, in run_command
    cmd_obj.run()
  File "setup.py", line 86, in run
    import tests as testsmodule
  File "/home/travis/build/python-bugzilla/python-bugzilla/tests/__init__.py", line 16, in <module>
    from bugzilla import Bugzilla, RHBugzilla
  File "/home/travis/build/python-bugzilla/python-bugzilla/bugzilla/__init__.py", line 13, in <module>
    from .base import Bugzilla
  File "/home/travis/build/python-bugzilla/python-bugzilla/bugzilla/base.py", line 35, in <module>
    from .bug import Bug, User
  File "/home/travis/build/python-bugzilla/python-bugzilla/bugzilla/bug.py", line 62
    return u"#%-6s %-10s - %s - %s" % (self.bug_id, self.bug_status,
                                  ^
SyntaxError: invalid syntax
```
https://travis-ci.org/python-bugzilla/python-bugzilla/jobs/261879390

**Comment by abn** [comment]
Looks like requests fails with 3.2 too. @crobinso got thoughts on this one? Reckon this is worth putting effort into?

https://travis-ci.org/python-bugzilla/python-bugzilla/jobs/261879390

**Comment by abn** [comment]
Requests no longer supports 3.2. https://github.com/requests/requests/issues/3507

**Comment by crobinso** [comment]
I think restricting versions like your patches do is the way to go
