### ISSUE TITLE
Show help if run without arguments

### ISSUE THREAD

**Issue by abitrolly** [python-bugzilla/python-bugzilla#68]
Running `bugzilla` without arguments leaves this trace:
```
➜  ~ bugzilla            
Traceback (most recent call last):
  File "/usr/bin/bugzilla", line 1117, in <module>
    main()
  File "/usr/bin/bugzilla", line 1108, in main
    raise RuntimeError("Unexpected action '%s'" % action)
RuntimeError: Unexpected action 'None'
```
I expected --help to be shown instead.

https://bugzilla.redhat.com/show_bug.cgi?id=1513819#c10

**Comment by crobinso** [comment]
Upstream fixed that issue awhile ago

```
$ python2 ./bugzilla-cli

usage: bugzilla-cli [-h] [--bugzilla BUGZILLA] [--nosslverify] [--cert CERT]
                    [--login] [--username USERNAME] [--password PASSWORD]
                    [--ensure-logged-in] [--no-cache-credentials]
                    [--cookiefile COOKIEFILE] [--tokenfile TOKENFILE]
                    [--verbose] [--debug] [--version]
                    {new,query,info,modify,attach,login} ...
bugzilla-cli: error: too few arguments
```
