### ISSUE TITLE
python-bugzilla's attach --getall fuunctionallity results in a backtrace

### ISSUE THREAD

**Issue by mcepl** [python-bugzilla/python-bugzilla#76]
(originally filed for [openSUSE](https://bugzilla.opensuse.org/show_bug.cgi?id=1062327))
Downloading all attachments of a bugzilla entry fails with:
```
jthumshirn@linux-x5ow:tmp$ bugzilla attach --getall 1060249
Traceback (most recent call last):
  File "/usr/bin/bugzilla", line 1130, in <module>
    main()
  File "/usr/bin/bugzilla", line 1108, in main
    _do_get_attach(bz, opt, parser, args)
  File "/usr/bin/bugzilla", line 931, in _do_get_attach
    opt.get += [a['id'] for a in bug.attachments]
  File "/usr/lib/python2.7/site-packages/bugzilla/bug.py", line 94, in __getattr__
    raise AttributeError("Bug object has no attribute '%s'" % name)
AttributeError: Bug object has no attribute 'attachments'
```
Downloading a single attachment 
```
jthumshirn@linux-x5ow:tmp$ bugzilla attach --get 741818
Wrote s390-sles12sp3-04-01-zfcp-fix-queuecommand-scsi_eh-commands-DIX.patch
```
happily succeeds.

**Comment by crobinso** [comment]
That bug.attachments code isn't in 2.1.0, so something is wrong somewhere. Either way upstream doesn't have this issue anymore, so closing
