### ISSUE TITLE
cant retrieve data

### ISSUE THREAD

**Issue by HEMA-MATHAVAN** [python-bugzilla/python-bugzilla#81]
Hi guys,
The following code throws error which i couldn rectify.i tried this https://bugzilla.redhat.com/show_bug.cgi?id=1215982, but i couldn downgrade python-urllib3 and requests as they are not available in the rpm.kindly state a solution

<import bugzilla

bz = bugzilla.Bugzilla(url='https://bugzilla.mozilla.org')
res=bz.getbugs([105825])
print type(res[0])
com_dic= res[0].getcomments()
print res[0].id
print res[0].summary  #summary
print com_dic[0]['text']  #description>

ERROR MESSAGE
.........................................................................................................
<class 'bugzilla.bug.Bug'>
Traceback (most recent call last):
  File "/home/hema/hema/work1/temp/bugzilla_mozilla.py", line 6, in <module>
    com_dic= res[0].getcomments()
  File "build/bdist.linux-x86_64/egg/bugzilla/bug.py", line 293, in getcomments
    comment_list = self.bugzilla.get_comments([self.bug_id])
  File "build/bdist.linux-x86_64/egg/bugzilla/base.py", line 1047, in get_comments
    return self._proxy.Bug.comments({'ids': idlist})
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "build/bdist.linux-x86_64/egg/bugzilla/transport.py", line 191, in request
    return self._request_helper(url, request_body)
  File "build/bdist.linux-x86_64/egg/bugzilla/transport.py", line 182, in _request_helper
    raise e
BugzillaError: not well-formed (invalid token): line 57, column 2

The

**Comment by HEMA-MATHAVAN** [comment]
this is also associated ,https://bugzilla.redhat.com/show_bug.cgi?id=468176. i am using fedora 23.

**Comment by crobinso** [comment]
Fedora 23 is very old, please reopen if you can reproduce on a newer Fedora version, using python bugzilla from git
