### ISSUE TITLE
Error while getting list of components

### ISSUE THREAD

**Issue by fpob** [python-bugzilla/python-bugzilla#86]
If I try to get list of components using

```python
bz_components = bz_api.getcomponents(BZ_PRODUCT_ID)
```
I get following error

```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    bz_components = bz_api.getcomponents(BZ_PRODUCT_ID)
  File "/home/fpoboril/.virtualenvs/tmp-923c07526c6838e/lib/python3.7/site-packages/bugzilla/base.py", line 881, in getcomponents
    product_id = proddict["id"]
KeyError: 'id'
```

This is problem in version 2.2.0. Older version 2.1.0 don't have this bug.

**Comment by crobinso** [comment]
Thanks for the report, looks like a legit bug, I've fixed it upstream now
