### ISSUE TITLE
`bugzilla info -c` crashes on "RH Ceph Storage" 

### ISSUE THREAD

**Issue by ktdreyer** [python-bugzilla/python-bugzilla#95]
Ran into a crash here with python-bugzilla-cli-2.2.0-3.fc29:

```
bugzilla info -c "RH Ceph Storage" 
Traceback (most recent call last):
  File "/usr/bin/bugzilla", line 11, in <module>
    load_entry_point('python-bugzilla==2.2.0', 'console_scripts', 'bugzilla')()
  File "/usr/lib/python3.7/site-packages/bugzilla/_cli.py", line 1178, in cli
    main()
  File "/usr/lib/python3.7/site-packages/bugzilla/_cli.py", line 1154, in main
    return _main(unittest_bz_instance)
  File "/usr/lib/python3.7/site-packages/bugzilla/_cli.py", line 1118, in _main
    _do_info(bz, opt)
  File "/usr/lib/python3.7/site-packages/bugzilla/_cli.py", line 628, in _do_info
    for name in sorted(bz.getcomponents(productname)):
  File "/usr/lib/python3.7/site-packages/bugzilla/base.py", line 881, in getcomponents
    product_id = proddict["id"]
KeyError: 'id'
```

It works fine for "Red Hat Enterprise Linux 7", so I'm not sure what's up.

**Comment by crobinso** [comment]
Thanks for the report Ken. It's an error reporting issue that's already fixed upstream. Upstream will give:

```
$ ./bugzilla-cli info -c "RH Ceph Storage" 
Server error: Product 'RH Ceph Storage' not found
```

And indeed the product name is 'Red Hat Ceph Storage' which works with upstream and current fedora releases.

**Comment by ktdreyer** [comment]
I should've known to check `master`! Thanks Cole!
